version: 1.4.0
port: 7054
debug: true
crlsizelimit: 512000
tls:
  enabled: false
ca:
  ca:
  name: org1-ca
  keyfile: /home/amalendum/internship/fabric-samples/org1-ca-key.pem
  certfile: /home/amalendum/internship/fabric-samples/org1-ca-cert.pem
  chainfile: /home/amalendum/internship/fabric-samples/org1-ca-chain.pem
registry:
  maxenrollments: -1
  identities:
    - name: admin
      pass: adminpw
      type: client
      affiliation: ""
      attrs:
        hf.Registrar.Roles: "*"
        hf.Registrar.DelegateRoles: "*"
        hf.Revoker: true
        hf.IntermediateCA: true
        hf.GenCRL: true
        hf.Registrar.Attributes: "*"
        hf.AffiliationMgr: true
db:
  type: sqlite3
  datasource: fabric-ca-server.db 